# Generated by Django 3.2.9 on 2021-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_id', models.CharField(max_length=7, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=15)),
                ('institution', models.CharField(max_length=15)),
                ('subjects_num', models.CharField(blank=True, max_length=6)),
                ('period', models.CharField(blank=True, max_length=10)),
                ('sort', models.CharField(max_length=10)),
                ('stage', models.CharField(blank=True, max_length=10)),
                ('range', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
