# Generated by Django 3.2.9 on 2021-11-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('period', models.CharField(blank=True, max_length=10)),
                ('scope', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=20)),
                ('phase', models.CharField(max_length=20)),
                ('subject_number', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'research_information',
            },
        ),
    ]
