# Generated by Django 3.2.9 on 2021-11-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchinformation',
            name='period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
