# Generated by Django 3.2.9 on 2021-11-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('interventional', '중재연구'), ('observational', '관찰연구')], max_length=50),
        ),
    ]
