# Generated by Django 3.2.9 on 2021-11-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developelist',
            name='period',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='developelist',
            name='target_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
