# Generated by Django 3.2.9 on 2021-11-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develope', '0002_auto_20211115_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developelist',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='developelist',
            name='subject',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
