# Generated by Django 3.2.9 on 2021-11-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develope', '0003_auto_20211115_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developelist',
            name='target_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
